name: N1-OpenWrt-CI

on:
  #schedule:
    #- cron: '0 22 * * *'
  watch:
    types: started
  repository_dispatch:
    types: run
    
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: [ubuntu-18.04]
    #if: github.event_name == 'schedule' || github.event.action == 'run'
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install depends
        run: |
          sudo swapoff /swapfile
          sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Clone Lean's openwrt
        run: |
          git clone https://github.com/coolsnowwolf/lede

      - name: Install feeds
        run: |
          cd lede

          # lede mod
          git clone https://github.com/tuanqing/lede-mod
          git apply lede-mod/patch/*.patch
          # luci-theme-bootstrap-mod & css patche
          svn co https://github.com/Lienol/openwrt-package/trunk/lienol/luci-theme-bootstrap-mod package/luci-theme-bootstrap-mod
          git clone https://github.com/tuanqing/bootstrap-mod
          git apply bootstrap-mod/patch/*.patch --directory=package/luci-theme-bootstrap-mod
          # n1 install program
          git clone https://github.com/tuanqing/install-program package/install-program

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Make config
        run: |
          cd lede

          cat > .config << EOF
          CONFIG_TARGET_armvirt=y
          CONFIG_TARGET_armvirt_64=y
          CONFIG_TARGET_armvirt_64_DEVICE_Phicomm-n1=y
          CONFIG_BRCMFMAC_SDIO=y
          CONFIG_PACKAGE_luci-app-haproxy-tcp=y
          # CONFIG_UnblockNeteaseMusic_NodeJS is not set
          EOF

          make defconfig
          ./scripts/feeds update -a

      - name: Compile openwrt
        run: |
          cd lede
          make download -j8
          make -j$(nproc) || make -j1 V=s

      - name: Build firmware
        run: |
          cp lede/bin/targets/*/*/*.tar.gz ./openwrt
          sudo ./make -d
          cp lede/.config out/config.seed

          cd out
          i=0
          kernels=("4.18.7" "4.19.106" "5.4.20")
          for x in ${kernels[*]}; do
            cd $x
            filename=$(ls)
            filename=${filename%.*}
            gzip *.img
            cd ../
            echo "::set-env name=firmware_$((++i))::$filename"
          done

      - name: Upload firmware @ kernel 4.18.7
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.firmware_1 }}
          path: out/4.18.7
      
      - name: Upload firmware @ kernel 4.19.106
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.firmware_2 }}
          path: out/4.19.106
      
      - name: Upload firmware @ kernel 5.4.20
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.firmware_3 }}
          path: out/5.4.20

      - name: Upload config file
        uses: actions/upload-artifact@master
        with:
          name: config
          path: out/config.seed
